[platformio]
src_dir = .

[env:seeed_xiao_esp32c3]
platform = espressif32@5.4.0
board = seeed_xiao_esp32c3
framework = arduino
build_src_filter = +<challenge3.cpp>
monitor_speed = 115200
upload_speed = 57600
upload_flags = --no-stub